name: publish docker image
on:
  push:
    path:
      - '.github/workflows/docker-image.yml'
      - 'sample-packages/docker/*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample-packages/docker
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: sandyabhat
          password: ${{ secrets.SAML_GIT_TOKEN}}
      - name: build-doker-image
        run: |
          docker build -t hello-docker .
          docker images
      - name: publish-image
        run: |
          docker tag hello-docker ghcr.io/SandyaBhat/hello-docker:latest
          docker push ghcr.io/SandyaBhat/hello-docker:latest